import { Station, Train, Amenity } from './types';

// Station database
export const stations: Station[] = [
  { id: 'BKK', name: 'กรุงเทพ (หัวลำโพง)', code: 'BKK', city: 'กรุงเทพมหานคร', region: 'กลาง' },
  { id: 'CNX', name: 'เชียงใหม่', code: 'CNX', city: 'เชียงใหม่', region: 'เหนือ' },
  { id: 'HYI', name: 'หาดใหญ่', code: 'HYI', city: 'หาดใหญ่', region: 'ใต้' },
  { id: 'NMA', name: 'นครราชสีมา', code: 'NMA', city: 'นครราชสีมา', region: 'ตะวันออกเฉียงเหนือ' },
  { id: 'UBN', name: 'อุบลราชธานี', code: 'UBN', city: 'อุบลราชธานี', region: 'ตะวันออกเฉียงเหนือ' },
  { id: 'KKN', name: 'ขอนแก่น', code: 'KKN', city: 'ขอนแก่น', region: 'ตะวันออกเฉียงเหนือ' },
  { id: 'PTY', name: 'พัทยา', code: 'PTY', city: 'พัทยา', region: 'ตะวันออก' },
  { id: 'AYA', name: 'พระนครศรีอยุธยา', code: 'AYA', city: 'พระนครศรีอยุธยา', region: 'กลาง' },
  { id: 'PKT', name: 'ภูเก็ต', code: 'PKT', city: 'ภูเก็ต', region: 'ใต้' },
  { id: 'LPG', name: 'ลำปาง', code: 'LPG', city: 'ลำปาง', region: 'เหนือ' },
  { id: 'SRT', name: 'สุราษฎร์ธานี', code: 'SRT', city: 'สุราษฎร์ธานี', region: 'ใต้' },
  { id: 'UDN', name: 'อุดรธานี', code: 'UDN', city: 'อุดรธานี', region: 'ตะวันออกเฉียงเหนือ' },
];

// Common amenities
const createAmenity = (id: string, name: string, icon: string, available: boolean = true): Amenity => ({
  id,
  name,
  icon,
  available,
});

const commonAmenities = {
  wifi: createAmenity('wifi', 'Wi-Fi ฟรี', '📶'),
  power: createAmenity('power', 'ปลั๊กไฟ', '🔌'),
  ac: createAmenity('ac', 'เครื่องปรับอากาศ', '❄️'),
  dining: createAmenity('dining', 'รถเสบียง', '🍽️'),
  accessible: createAmenity('accessible', 'เข้าถึงได้สำหรับผู้พิการ', '♿'),
  luggage: createAmenity('luggage', 'ที่เก็บกระเป๋า', '🧳'),
  toilet: createAmenity('toilet', 'ห้องน้ำ', '🚻'),
  sleeper: createAmenity('sleeper', 'ที่นอน', '🛏️'),
};

// Train database
export const trains: Train[] = [
  {
    id: 'T001',
    trainNumber: 'SP001',
    trainName: 'ด่วนพิเศษกรุงเทพ-เชียงใหม่',
    origin: 'BKK',
    destination: 'CNX',
    departureTime: '08:30',
    arrivalTime: '20:15',
    duration: '11ชม. 45นาที',
    stops: ['AYA', 'LPG'],
    classes: [
      {
        id: 'first',
        name: 'ชั้น 1',
        price: 1850,
        features: ['ที่นั่งปรับเอนได้', 'Wi-Fi ความเร็วสูง', 'อาหารว่างฟรี', 'ห้องน้ำส่วนตัว'],
        available: 12,
        totalSeats: 20,
      },
      {
        id: 'business',
        name: 'ชั้นธุรกิจ',
        price: 1250,
        features: ['ที่นั่งสบาย', 'Wi-Fi', 'เครื่องดื่มฟรี', 'ปลั๊กไฟ'],
        available: 28,
        totalSeats: 40,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 650,
        features: ['ที่นั่งมาตรฐาน', 'ปลั๊กไฟ', 'ห้องน้ำรวม'],
        available: 45,
        totalSeats: 80,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.dining,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
    ],
    operatingDays: ['daily'],
  },
  {
    id: 'T002',
    trainNumber: 'SP002',
    trainName: 'ด่วนพิเศษกรุงเทพ-หาดใหญ่',
    origin: 'BKK',
    destination: 'HYI',
    departureTime: '14:45',
    arrivalTime: '05:30',
    duration: '14ชม. 45นาที',
    stops: ['SRT'],
    classes: [
      {
        id: 'first',
        name: 'ชั้น 1 (นอน)',
        price: 2150,
        features: ['ที่นอนส่วนตัว', 'Wi-Fi', 'อาหารเช้าฟรี', 'ห้องน้ำในห้อง'],
        available: 8,
        totalSeats: 16,
      },
      {
        id: 'business',
        name: 'ชั้นธุรกิจ (นอน)',
        price: 1450,
        features: ['ที่นอนแบบแชร์', 'Wi-Fi', 'ผ้าห่มหมอน', 'ห้องน้ำรวม'],
        available: 20,
        totalSeats: 32,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 750,
        features: ['ที่นั่งเอนได้', 'ปลั๊กไฟ', 'ห้องน้ำรวม'],
        available: 50,
        totalSeats: 80,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.dining,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
      commonAmenities.sleeper,
    ],
    operatingDays: ['daily'],
  },
  {
    id: 'T003',
    trainNumber: 'EX101',
    trainName: 'ด่วนกรุงเทพ-นครราชสีมา',
    origin: 'BKK',
    destination: 'NMA',
    departureTime: '06:00',
    arrivalTime: '10:30',
    duration: '4ชม. 30นาที',
    stops: ['AYA'],
    classes: [
      {
        id: 'business',
        name: 'ชั้นธุรกิจ',
        price: 550,
        features: ['ที่นั่งกว้าง', 'Wi-Fi', 'ปลั๊กไฟ'],
        available: 35,
        totalSeats: 50,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 280,
        features: ['ที่นั่งมาตรฐาน', 'ปลั๊กไฟ'],
        available: 60,
        totalSeats: 100,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
    ],
    operatingDays: ['daily'],
  },
  {
    id: 'T004',
    trainNumber: 'SP003',
    trainName: 'ด่วนพิเศษกรุงเทพ-อุบลราชธานี',
    origin: 'BKK',
    destination: 'UBN',
    departureTime: '20:00',
    arrivalTime: '07:45',
    duration: '11ชม. 45นาที',
    stops: ['NMA', 'KKN'],
    classes: [
      {
        id: 'first',
        name: 'ชั้น 1 (นอน)',
        price: 1950,
        features: ['ห้องนอนส่วนตัว', 'Wi-Fi', 'อาหารเช้า', 'ห้องน้ำในห้อง'],
        available: 10,
        totalSeats: 16,
      },
      {
        id: 'business',
        name: 'ชั้นธุรกิจ (นอน)',
        price: 1350,
        features: ['ที่นอน 2 ชั้น', 'Wi-Fi', 'ผ้าห่ม', 'ปลั๊กไฟ'],
        available: 25,
        totalSeats: 40,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 580,
        features: ['ที่นั่งเอน', 'ห้องน้ำรวม'],
        available: 55,
        totalSeats: 80,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.dining,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
      commonAmenities.sleeper,
    ],
    operatingDays: ['daily'],
  },
  {
    id: 'T005',
    trainNumber: 'EX102',
    trainName: 'ด่วนกรุงเทพ-ขอนแก่น',
    origin: 'BKK',
    destination: 'KKN',
    departureTime: '07:30',
    arrivalTime: '14:00',
    duration: '6ชม. 30นาที',
    stops: ['AYA', 'NMA'],
    classes: [
      {
        id: 'business',
        name: 'ชั้นธุรกิจ',
        price: 750,
        features: ['ที่นั่งสบาย', 'Wi-Fi', 'เครื่องดื่ม', 'ปลั๊กไฟ'],
        available: 30,
        totalSeats: 45,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 380,
        features: ['ที่นั่งมาตรฐาน', 'ปลั๊กไฟ'],
        available: 65,
        totalSeats: 90,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.dining,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
    ],
    operatingDays: ['daily'],
  },
  {
    id: 'T006',
    trainNumber: 'SP004',
    trainName: 'ด่วนพิเศษเชียงใหม่-กรุงเทพ',
    origin: 'CNX',
    destination: 'BKK',
    departureTime: '17:00',
    arrivalTime: '05:15',
    duration: '12ชม. 15นาที',
    stops: ['LPG', 'AYA'],
    classes: [
      {
        id: 'first',
        name: 'ชั้น 1 (นอน)',
        price: 1950,
        features: ['ห้องนอนส่วนตัว', 'Wi-Fi', 'อาหารเช้า', 'ห้องน้ำในห้อง'],
        available: 14,
        totalSeats: 20,
      },
      {
        id: 'business',
        name: 'ชั้นธุรกิจ (นอน)',
        price: 1350,
        features: ['ที่นอน', 'Wi-Fi', 'ผ้าห่มหมอน', 'ปลั๊กไฟ'],
        available: 32,
        totalSeats: 40,
      },
      {
        id: 'economy',
        name: 'ชั้นประหยัด',
        price: 680,
        features: ['ที่นั่ง', 'ห้องน้ำรวม'],
        available: 48,
        totalSeats: 80,
      },
    ],
    amenities: [
      commonAmenities.wifi,
      commonAmenities.power,
      commonAmenities.ac,
      commonAmenities.dining,
      commonAmenities.accessible,
      commonAmenities.luggage,
      commonAmenities.toilet,
      commonAmenities.sleeper,
    ],
    operatingDays: ['daily'],
  },
];

// Helper function to get station by ID
export const getStationById = (id: string): Station | undefined => {
  return stations.find(station => station.id === id);
};

// Helper function to get station name
export const getStationName = (id: string): string => {
  const station = getStationById(id);
  return station ? station.name : id;
};
